spring.application.name=stock-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/stockdb?options=-c%20timezone=UTC
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.jwt.secret=${JWT_SECRET:stock-portfolio-manager-jwt-secret-key}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
